name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-amd64
            artifact: velora-linux-amd64
            install: sudo apt-get install -y llvm-dev clang

          - os: ubuntu-24.04-arm
            target: linux-arm64
            artifact: velora-linux-arm64
            install: sudo apt-get install -y llvm-dev clang

          - os: macos-latest
            target: darwin-arm64
            artifact: velora-darwin-arm64
            install: brew install llvm

          # - os: windows-latest
          #   target: windows-amd64
          #   artifact: velora-windows-amd64.exe
          #   install: choco install llvm

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install LLVM
        env: 
          HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
        run: ${{ matrix.install }}

      - name: Build (unix)
        if: runner.os != 'Windows'
        run: |
          # add homebrew llvm to path on mac
          if [ "$RUNNER_OS" = "macOS" ]; then
            export PATH="$(brew --prefix llvm)/bin:$PATH"
          fi

          mkdir -p dist
          clang ./src/*.c ./src/*/*.c\
            -o dist/${{ matrix.artifact }} \
            -Wall -Wextra \
            -DVERSION=\"${{ github.ref_name }}\" \
            -DCOMMIT=\"$(git rev-parse --short HEAD)\" \
            -DDATE=\"$(date +%Y-%m-%d)\" \
            $(llvm-config --cflags --ldflags --libs core analysis native) \
            -lpthread -lm -ldl

      # - name: Build (windows)
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     mkdir dist
      #     for /f "tokens=*" %%i in ('llvm-config --cflags --ldflags --libs core analysis native') do set LLVM_FLAGS=%%i
      #     clang ./src/*.c -o dist/${{ matrix.artifact }} -Wall -Wextra -DVERSION="%{{ github.ref_name }}%" %LLVM_FLAGS%

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: dist/${{ matrix.artifact }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name:     ${{ github.ref_name }}
          files:    dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
